### ISSUE TITLE
[BUG] windows-dooit.exe - 3.0.4: Crash at startup.

### ISSUE THREAD

**Issue by KF-Tarsier** [dooit-org/dooit#217]
**Describe the bug** 🐛
Version 3.0.4 of windows-dooit.exe crashes at startup.

**To Reproduce** 🐣
1. Download version 3.0.4 of windows-doot.exe from github.
2. Open terminal in the folder containing windows-dooit.exe
3. Run .\windows-dooit.exe
4. windows-dooit.exe aborts startup and command finishes.

**Expected behavior**  🤔 
windows-dooit.exe starts successfully.

**Screenshots** 🧐
Instead of a screenshot, the terminal output is shown.
```
D:\Projects
❯ .\windows-dooit.exe
Traceback (most recent call last):
  File "sqlalchemy\engine\base.py", line 146, in __init__
  File "sqlalchemy\engine\base.py", line 3302, in raw_connection
  File "sqlalchemy\pool\base.py", line 449, in connect
  File "sqlalchemy\pool\base.py", line 1263, in _checkout
  File "sqlalchemy\pool\base.py", line 712, in checkout
  File "sqlalchemy\pool\impl.py", line 179, in _do_get
  File "sqlalchemy\util\langhelpers.py", line 146, in __exit__
  File "sqlalchemy\pool\impl.py", line 177, in _do_get
  File "sqlalchemy\pool\base.py", line 390, in _create_connection
  File "sqlalchemy\pool\base.py", line 674, in __init__
  File "sqlalchemy\pool\base.py", line 900, in __connect
  File "sqlalchemy\util\langhelpers.py", line 146, in __exit__
  File "sqlalchemy\pool\base.py", line 896, in __connect
  File "sqlalchemy\engine\create.py", line 643, in connect
  File "sqlalchemy\engine\default.py", line 621, in connect
sqlite3.OperationalError: unable to open database file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "dooit.py", line 2, in <module>
  File "click\core.py", line 1157, in __call__
  File "click\core.py", line 1078, in main
  File "click\core.py", line 1666, in invoke
  File "click\core.py", line 1434, in invoke
  File "click\core.py", line 783, in invoke
  File "click\decorators.py", line 33, in new_func
  File "dooit\__main__.py", line 40, in main
  File "dooit\__main__.py", line 12, in run_dooit
  File "dooit\ui\tui.py", line 38, in __init__
  File "dooit\api\manager.py", line 22, in connect
  File "sqlalchemy\sql\schema.py", line 5868, in create_all
  File "sqlalchemy\engine\base.py", line 3252, in _run_ddl_visitor
  File "contextlib.py", line 137, in __enter__
  File "sqlalchemy\engine\base.py", line 3242, in begin
  File "sqlalchemy\engine\base.py", line 3278, in connect
  File "sqlalchemy\engine\base.py", line 148, in __init__
  File "sqlalchemy\engine\base.py", line 2442, in _handle_dbapi_exception_noconnection
  File "sqlalchemy\engine\base.py", line 146, in __init__
  File "sqlalchemy\engine\base.py", line 3302, in raw_connection
  File "sqlalchemy\pool\base.py", line 449, in connect
  File "sqlalchemy\pool\base.py", line 1263, in _checkout
  File "sqlalchemy\pool\base.py", line 712, in checkout
  File "sqlalchemy\pool\impl.py", line 179, in _do_get
  File "sqlalchemy\util\langhelpers.py", line 146, in __exit__
  File "sqlalchemy\pool\impl.py", line 177, in _do_get
  File "sqlalchemy\pool\base.py", line 390, in _create_connection
  File "sqlalchemy\pool\base.py", line 674, in __init__
  File "sqlalchemy\pool\base.py", line 900, in __connect
  File "sqlalchemy\util\langhelpers.py", line 146, in __exit__
  File "sqlalchemy\pool\base.py", line 896, in __connect
  File "sqlalchemy\engine\create.py", line 643, in connect
  File "sqlalchemy\engine\default.py", line 621, in connect
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
(Background on this error at: https://sqlalche.me/e/20/e3q8)
[PYI-33708:ERROR] Failed to execute script 'dooit' due to unhandled exception!

D:\Projects took 2s
❯
```

**Desktop (please complete the following information):**  🤖
 - OS: Microsoft Windows 10 Pro
 - Version: 10.0.19045 Build 19045

**Comment by kraanzu** [comment]
Ah this this issue was fixed but has not been released yet. Are you willing to install via pip? I was busy so was not able to do a new release
